

######################
# Load libraries and data
######################

library(dplyr)
library(stringr)
library(readxl)

quality_of_govt <- read_excel("data/country_characteristics/la_porta_data/Quality_of_Govt.xlsx", 
                              sheet = "data")

ctry_profiles <- read.csv("data/country_characteristics/ctry_profiles.csv")


######################
# clean
######################

quality_of_govt <- quality_of_govt %>%
  mutate(contcode_norm = str_trim(tolower(contcode)))

iso2_map <- c(
  "afghanistan" = "AF",
  "antigua and barbuda" = "AG",
  "iraq" = "IQ",
  "lao, people's dem rep." = "LA",
  "somalia" = "SO",
  "korea, dem. re" = "KP",
  "haiti" = "HT",
  "rwanda" = "RW",
  "libya" = "LY",
  "cuba" = "CU",
  "vietnam" = "VN",
  "iran, islamic" = "IR",
  "cameroon" = "CM",
  "dominican republic" = "DO",
  "ethiopia" = "ET",
  "romania" = "RO",
  "azerbaijan" = "AZ",
  "china" = "CN",
  "sierra leone" = "SL",
  "myanmar" = "MM",
  "congo" = "CG",
  "georgia" = "GE",
  "chad" = "TD",
  "bangladesh" = "BD",
  "burundi" = "BI",
  "syrian arab republic" = "SY",
  "guinea" = "GN",
  "angola" = "AO",
  "yemen, rep." = "YE",
  "cote d'ivoire" = "CI",
  "croatia" = "HR",
  "cambodia" = "KH",
  "mozambique" = "MZ",
  "mauritania" = "MR",
  "nicaragua" = "NI",
  "sudan" = "SD",
  "mali" = "ML",
  "fiji" = "FJ",
  "equatorial guinea" = "GQ",
  "burkina faso" = "BF",
  "nepal" = "NP",
  "papua new guin" = "PG",
  "lesotho" = "LS",
  "nigeria" = "NG",
  "el salvador" = "SV",
  "slovak republi" = "SK",
  "niger" = "NE",
  "barbados" = "BB",
  "djibouti" = "DJ",
  "belarus" = "BY",
  "bulgaria" = "BG",
  "algeria" = "DZ",
  "costa rica" = "CR",
  "guatemala" = "GT",
  "venezuela" = "VE",
  "guyana" = "GY",
  "sri lanka" = "LK",
  "suriname" = "SR",
  "malta" = "MT",
  "south africa" = "ZA",
  "russian federation" = "RU",
  "malawi" = "MW",
  "lithuania" = "LT",
  "bolivia" = "BO",
  "indonesia" = "ID",
  "lebanon" = "LB",
  "colombia" = "CO",
  "mexico" = "MX",
  "benin" = "BJ",
  "zambia" = "ZM",
  "paraguay" = "PY",
  "india" = "IN",
  "gabon" = "GA",
  "mongolia" = "MN",
  "cyprus" = "CY",
  "ghana" = "GH",
  "honduras" = "HN",
  "albania" = "AL",
  "peru" = "PE",
  "panama" = "PA",
  "zimbabwe" = "ZW",
  "egypt, arab republic" = "EG",
  "madagascar" = "MG",
  "ukraine" = "UA",
  "brazil" = "BR",
  "tanzania" = "TZ",
  "slovenia" = "SI",
  "tunisia" = "TN",
  "moldova" = "MD",
  "armenia" = "AM",
  "kenya" = "KE",
  "gambia, the" = "GM",
  "jamaica" = "JM",
  "philippines" = "PH",
  "israel" = "IL",
  "spain" = "ES",
  "poland" = "PL",
  "turkey" = "TR",
  "italy" = "IT",
  "morocco" = "MA",
  "belize" = "BZ",
  "greece" = "GR",
  "uruguay" = "UY",
  "sweden" = "SE",
  "namibia" = "NAM",
  "cape verde" = "CV",
  "hungary" = "HU",
  "liechtenstein" = "LI",
  "estonia" = "EE",
  "czech republic" = "CZ",
  "latvia" = "LV",
  "botswana" = "BW",
  "pakistan" = "PK",
  "portugal" = "PT",
  "oman" = "OM",
  "jordan" = "JO",
  "uganda" = "UG",
  "malaysia" = "MY",
  "france" = "FR",
  "senegal" = "SN",
  "argentina" = "AR",
  "australia" = "AU",
  "germany" = "DE",
  "belgium" = "BE",
  "netherlands" = "NL",
  "new zealand" = "NZ",
  "switzerland" = "CH",
  "canada" = "CA",
  "iceland" = "IS",
  "luxembourg" = "LU",
  "swaziland" = "SZ",
  "bahamas, the" = "BS",
  "korea, rep." = "KR",
  "singapore" = "SG",
  "chile" = "CL",
  "bahrain" = "BH",
  "norway" = "NO",
  "saudi arabia" = "SA",
  "japan" = "JP",
  "ireland" = "IE",
  "denmark" = "DK",
  "st. vincent antilles" = "VC",
  "united arab emirates" = "AE",
  "finland" = "FI",
  "united states" = "US",
  "trinidad and tobago" = "TT",
  "austria" = "AT",
  "thailand" = "TH",
  "united kingdom" = "GB",
  "kuwait" = "KW",
  "ecuador" = "EC",
  "liberia" = "LR",
  "maldives" = "MV",
  "eritrea" = "ER",
  "mauritius" = "MU",
  "st. lucia" = "LC",
  "andorra" = "AD",
  "montenegro" = "ME",
  "guinea-bissau" = "GW",
  "kyrgyz republic" = "KG",
  "tajikistan" = "TJ",
  "kazakstan" = "KZ",
  "grenada" = "GD",
  "marshall islan" = "MH",
  "togo" = "TG",
  "turkmenistan" = "TM",
  "uzbekistan" = "UZ",
  "kiribati" = "KI",
  "brunei" = "BN",
  "bosnia and herzegovina" = "BA",
  "macedonia (fmr.yugouslavia)" = "MK",
  "bhutan" = "BT",
  "tuvalu" = "TV",
  "western samoa" = "WS",
  "st. kitts and nevis" = "KN",
  "dominica" = "DM",
  "qatar" = "QA",
  "vanuatu" = "VU",
  "tonga" = "TO",
  "sao tome and principe" = "ST",
  "seychelles" = "SC",
  "monaco" = "MC",
  "congo (kin)" = "CD",
  "comorro island" = "KM",
  "micronesia, federal states" = "FM",
  "central africa" = "CF"
)

dt <- quality_of_govt %>%
  mutate(ctry = recode(contcode_norm, !!!iso2_map, .default = NA_character_)) %>%
  select(-contcode_norm) %>% 
  filter(!is.na(ctry)) %>%
  select(ctry, legor_uk, legor_fr, legor_so, legor_ge, legor_sc)

# Handle Namibia
dt$ctry[dt$ctry %in% "NAM"] <- "NA"

############################
# Save
############################
write.csv(dt, "data/country_characteristics/la_porta_data/legal_origin_data.csv", row.names = FALSE)



